apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        node-type: karpenter
    spec:
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values: ["t", "m", "c"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand", "spot"]
  limits:
    cpu: "100"
      
