apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ekart
  template:
    metadata:
      labels:
        app: ekart
    spec:
      containers:
      - name: ekart-container
        image: "gowdas1997/e-kart-new-image:latest"
        ports:
        - containerPort: 8070
        
        
